import {
  type Brand,
  fontLabel,
  googleParamFor,
  readableOn,
  pillRadius,
  slug,
} from "./brand";

/** brand.tokens.css — the design-side variables (also usable in any web build). */
export function tokensCss(b: Brand): string {
  return `:root {
  --brand-accent: ${b.accent};
  --brand-accent-ink: ${readableOn(b.accent)};
  --brand-ink: ${b.ink};
  --brand-paper: ${b.paper};
  --brand-surface: #ffffff;
  --brand-font-display: ${b.displayFont};
  --brand-font-body: ${b.bodyFont};
  --brand-radius: ${b.radius}px;
  --brand-radius-pill: ${pillRadius(b.buttonShape)};
}
`;
}

/** brand.liquid — a drop-in Shopify snippet: fonts + CSS variables + base styling. */
export function liquidSnippet(b: Brand): string {
  const families = [...new Set([b.displayFont, b.bodyFont].map(googleParamFor).filter(Boolean))];
  const href = `https://fonts.googleapis.com/css2?${families.map((f) => `family=${f}`).join("&")}&display=swap`;
  return `{%- comment -%}
  ${b.name} — brand kit generated by Brand Studio.
  Install: in layout/theme.liquid <head>, add  {% render 'brand' %}
  Tip: replace the hardcoded values below with {{ settings.* }} to wire them
  into the theme customizer.
{%- endcomment -%}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="${href}" rel="stylesheet">
<style>
  :root {
    --brand-accent: {{ settings.brand_accent | default: '${b.accent}' }};
    --brand-accent-ink: ${readableOn(b.accent)};
    --brand-ink: ${b.ink};
    --brand-paper: ${b.paper};
    --brand-surface: #ffffff;
    --brand-font-display: ${b.displayFont};
    --brand-font-body: ${b.bodyFont};
    --brand-radius: ${b.radius}px;
    --brand-radius-pill: ${pillRadius(b.buttonShape)};
  }
  body {
    background: var(--brand-paper);
    color: var(--brand-ink);
    font-family: var(--brand-font-body);
  }
  h1, h2, h3, .h-display { font-family: var(--brand-font-display); }
  .btn, .button, button.button, .product-form__submit {
    background: var(--brand-accent);
    color: var(--brand-accent-ink);
    border-radius: var(--brand-radius-pill);
    border: 0;
  }
  .card, .card-wrapper, .product-card { border-radius: var(--brand-radius); }
</style>
`;
}

/** CLAUDE.md — the brand spec Claude Code reads before building this brand's site. */
export function claudeMd(b: Brand): string {
  return `# ${b.name} — Brand Spec

> Read this before building or editing the **${b.name}** storefront. Apply it to every
> section, snippet, and component. This file is the source of truth; \`snippets/brand.liquid\`
> exposes the same values as CSS variables in the theme.

## Palette

| Token | Value | Use |
| --- | --- | --- |
| Accent | \`${b.accent}\` | buttons, links, highlights, sale prices |
| Accent text | \`${readableOn(b.accent)}\` | text/icons on accent fills |
| Ink | \`${b.ink}\` | body text, headings |
| Paper | \`${b.paper}\` | page background |
| Surface | \`#ffffff\` | cards, sheets |

## Typography

- **Display (headings):** ${fontLabel(b.displayFont)} — \`var(--brand-font-display)\`
- **Body (text & UI):** ${fontLabel(b.bodyFont)} — \`var(--brand-font-body)\`

## Shape

- **Buttons:** ${b.buttonShape} — \`var(--brand-radius-pill)\` = \`${pillRadius(b.buttonShape)}\`
- **Cards / inputs:** ${b.radius}px — \`var(--brand-radius)\`

## Rules when building

- **Never hardcode hex or fonts.** Use the \`--brand-*\` CSS variables from \`snippets/brand.liquid\`.
- Headings use the display font; everything else uses the body font.
- Primary CTAs (Add to cart, Shop now, Subscribe) use the accent fill, accent-text color, and the button radius above.
- Keep spacing generous — section padding ~64px desktop, ~32px mobile.
- Match the section vocabulary below; don't invent new section types without a reason.

## Section vocabulary (typical DTC storefront)

- **Announcement bar** — shipping/returns/promo, ink background, small text.
- **Hero** — full-bleed, eyebrow + display headline + accent CTA.
- **Product card** — 4:5 image, display-font title, price (compare-at renders as strikethrough), star rating, accent add-to-cart.
- **Newsletter** — email capture with accent submit; offer the first-order discount.
- **Footer** — wordmark + links, paper or ink background.

## Source of truth

- CSS variables: \`snippets/brand.liquid\`  (render it in \`<head>\`)
- Machine-readable tokens: \`brand.json\`
- Domain: ${slug(b.name)}.com
`;
}

/** brand.json — machine-readable tokens for any tool in the pipeline. */
export function brandJson(b: Brand): string {
  return JSON.stringify(
    {
      name: b.name,
      slug: slug(b.name),
      colors: {
        accent: b.accent,
        accentInk: readableOn(b.accent),
        ink: b.ink,
        paper: b.paper,
        surface: "#ffffff",
      },
      fonts: {
        display: fontLabel(b.displayFont),
        body: fontLabel(b.bodyFont),
        displayStack: b.displayFont,
        bodyStack: b.bodyFont,
      },
      shape: {
        buttons: b.buttonShape,
        buttonRadius: pillRadius(b.buttonShape),
        radiusPx: b.radius,
      },
    },
    null,
    2
  );
}

export interface ExportFile {
  id: string;
  filename: string;
  language: string;
  build: (b: Brand) => string;
}

export const EXPORTS: ExportFile[] = [
  { id: "claude", filename: "CLAUDE.md", language: "markdown", build: claudeMd },
  { id: "liquid", filename: "brand.liquid", language: "liquid", build: liquidSnippet },
  { id: "tokens", filename: "brand.tokens.css", language: "css", build: tokensCss },
  { id: "json", filename: "brand.json", language: "json", build: brandJson },
];
